### ISSUE TITLE
sm15986625 で例外吐く

### ISSUE THREAD

**Issue by roronya** [roronya/gazeru#17]
```
downloading Remember - neko
[==================================================] 100%
Traceback (most recent call last):
  File "/usr/local/bin/gazeru", line 94, in <module>
    args.func(args)
  File "/usr/local/bin/gazeru", line 44, in pull
    gazeru.pull()
  File "/usr/local/lib/python3.4/dist-packages/gazeru/gazeru.py", line 136, in pull
    video, video_type = self.download_video(video_info['id'])
  File "/usr/local/lib/python3.4/dist-packages/gazeru/gazeru.py", line 199, in download_video
    video_info = nicopy.get_video_info(video_id)
  File "/usr/local/lib/python3.4/dist-packages/nicopy/nicopy.py", line 28, in get_video_info
    thumb_info = {'video_id': soup.find('video_id'), 'title': soup.find('title').get_text(),
AttributeError: 'NoneType' object has no attribute 'get_text'

```

**Comment by roronya** [comment]
nicopy で直接 get_video_info 叩いた時は例外吐かない

**Comment by roronya** [comment]
```
aoi@aoi:~/gazeru$ gazeru pull
downloading Remember - neko
b'<?xml version="1.0" encoding="UTF-8"?>\n<nicovideo_thumb_response status="fail">\n  <error>\n    <code>COMMUNITY</code>\n    <description>community</description>\n  </error>\n</nicovideo_thumb_response>'
None
```

なるほど、コミュニティ限定の曲だ

クッキー渡して get_thumb_info 叩けば解決できるんじゃないかな

**Comment by roronya** [comment]
いやちがうな？？違うホストから試してもこんな表示されないもんな

**Comment by roronya** [comment]
http://ext.nicovideo.jp/api/getthumbinfo/1319545065

sm~~ 形式でないと community とだけ書かれた xml かえってくるみたい

**Comment by roronya** [comment]
http://ext.nicovideo.jp/api/getthumbinfo/sm15986625
`
<nicovideo_thumb_response status="ok">`

一番最初の行の status みて fail ならスキップするようにする

**Comment by roronya** [comment]
https://github.com/roronya/gazeru/commit/d1ad36829de93210bc5d9a1dae119c43df4632cc

解消した
